spring.application.name=backend
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/hrplatform?stringtype=unspecified
spring.datasource.username=postgres
spring.datasource.password=1Woogatagah

# Server port
server.port=8080

# Logging
logging.level.root=INFO
logging.level.com.hrplatform=DEBUG

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mohammed.serrafi.00@gmail.com
spring.mail.password=qfvslvtcramtasck
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
